name: Update EPG

on:
  # Manuelles Starten weiterhin möglich
  workflow_dispatch:

  # Zweimal täglich:
  #
  # 03:00 UTC
  # 15:00 UTC
  #
  # Damit entstehen zwei verschiedene 24-Stunden-Fenster:
  #
  # 03:00-Lauf:
  # 00:00 -> 00:00 nächster Tag
  #
  # 15:00-Lauf:
  # 12:00 -> 12:00 nächster Tag
  schedule:
    - cron: "0 3,15 * * *"


# ============================================================
# BERECHTIGUNGEN
# ============================================================

permissions:
  contents: read
  pages: write
  id-token: write


# ============================================================
# VERHINDERT MEHRERE GLEICHZEITIGE DEPLOYMENTS
# ============================================================

concurrency:
  group: "pages"
  cancel-in-progress: true


# ============================================================
# BUILD
# ============================================================

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      # ------------------------------------------------------
      # Repository auschecken
      # ------------------------------------------------------

      - name: Repository auschecken
        uses: actions/checkout@v6


      # ------------------------------------------------------
      # Python einrichten
      # ------------------------------------------------------

      - name: Python einrichten
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"


      # ------------------------------------------------------
      # EPG herunterladen und filtern
      # ------------------------------------------------------

      - name: EPG filtern
        run: python epg_filter.py


      # ------------------------------------------------------
      # GitHub Pages vorbereiten
      # ------------------------------------------------------

      - name: GitHub Pages vorbereiten
        uses: actions/configure-pages@v6


      # ------------------------------------------------------
      # EPG für GitHub Pages bereitstellen
      # ------------------------------------------------------

      - name: EPG für Pages vorbereiten
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./public


# ============================================================
# DEPLOY
# ============================================================

  deploy:
    needs: build

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      # ------------------------------------------------------
      # EPG veröffentlichen
      # ------------------------------------------------------

      - name: EPG veröffentlichen
        id: deployment
        uses: actions/deploy-pages@v5
